services:
  - type: web
    name: sub-tracker-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_URL
        sync: false
      - key: DEFAULT_TIMEZONE
        value: UTC+3
      - key: REMINDER_HOUR
        value: "10"
      - key: REMINDER_MINUTE
        value: "0"
